server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      #连接池配置
      pool-name: DateHikariCP
      #最小链接数
      minimum-idle: 5
      #空闲链接存活最大时间，默认600000（10min）
      idle-timeout: 180000
      #最大连接数，默认10
      maximum-pool-size: 10
      #从链接池返回的链接自动提交
      auto-commit: true
      #链接最大存活时间，默认1800000（30min）
      max-lifetime: 1800000
      #链接超时间，默认30000（30s）
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1
  main:
    allow-circular-references: true
  #Use this to befriend spring-boot-starter-actuator & springfox-boot-starter
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis-plus:
  #配置Mapper映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名（默认别名是类名）
  type-aliases-package: com.example.server.pojo
  configuration:
    #自动驼峰命名
    map-underscore-to-camel-case: false

## Mybatis SQL 打印（方法接口所在的包，不是Mapper。xml所在的包）
logging:
  level:
    com.example.server.mapper: debug


jwt:
  #jwt存储的请求头
  tokenHeader: Authorization
  #jwt 加解密使用的密钥
  secret: yeb-secret
  #jwt的超期限时间(S)
  expiration: 604800
  #jwt负载中拿到的开头
  tokenHead: Bearer



